# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671e77e1574a5be6a771bc0ca7efe9d4f53928207b7cc3098668c7c37edbe95924a86a1234fdeeb5c5860513b5a013f373ca4dfc73d6d83ed5ff84cb36a4a499

test:
  secret_key_base: f21b93d82f0787a8ff9eed06e66ddf5a63828a82a16197deed86bdcfc2bcd9c42d165b4fb2b901c27b7dd9ebbe00a143a252cefa69a09dd2b508e6cdea091520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
